### ISSUE TITLE
Ampliar a base de dados

### ISSUE THREAD

**Issue by Fideliszan** [HaraHeique/TCC-rede-neural-siamesa#11]
Atente-se aos nomes dos autores: William Faulkner, Ernest Hemingway, Philip Roth

### Treinamento

**12 mil frases de cada**

1, 2, Frase1, Frase 2, Faulkner até 11999,12000, Frase11999, Frase 12000, Faulkner

12001, 12002, Frase12001, Frase 12002, Roth até 23999,24000, Frase23999, Frase 24000, Roth

24001, 24002, Frase24001, Frase 24002, Hemingway até 35999,36000, Frase35999, Frase 36000, Hemingway

### Predição
180 e 600 (ampliação de 6x) seguindo o mesmo padrão do csv.
**Estilo:** Frase1, Frase2 em dois arquivos csv.
A primeira coluna sempre do mesmo autor e a segunda coluna aleatória.

Como fazer?
- Entre em http://libgen.rs/
- Digite os nomes dos autores e baixe vários **epub's** deles; 
- De dentro dos epub's extraia o texto plain (txt) (**uma possibilidade** é usar o Calibre);
- Usando a biblioteca nltk separe os txts no formato de frases separadas;
- Atenção: limpeza e preparação dos dados (pré-processamento):
https://machinelearningmastery.com/clean-text-machine-learning-python/

**Comment by HaraHeique** [comment]
@Fideliszan, ferramenta online que achei para converter de diversos formatos para diversos formatos (incluindo .pdf, .epub, .lit e afins): https://cloudconvert.com/

**Comment by HaraHeique** [comment]
@Fideliszan, pegue em torno de 5/6 obras de cada autor e converti todos no formato _txt_. Abaixo estão os commits que contém os arquivos upados neste repositório remoto:

- ea6b9bdbd3f4dbf70ae8b338ad12d614b86a9947: [Link](https://github.com/HaraHeique/TCC-rede-neural-siamesa/tree/master/docs/literary_works) com o diretório dos arquivos em seu formato bruto;
- f2ee870e3772cd81eb66aa933c449ce0cee0364f: [Link](https://github.com/HaraHeique/TCC-rede-neural-siamesa/tree/master/src/data/works) com o diretório dos arquivos em txt.

**Comment by HaraHeique** [comment]
Fechei o issue sem querer.

**Comment by HaraHeique** [comment]
Salvando alguns links referentes a leitura, preparacao e pre processamento dos dados:

- https://linuxhint.com/extract_sentences_nltk_python_module/
- https://www.nltk.org/book/ch03.html
- https://datatofish.com/export-dataframe-to-csv/
- https://realpython.com/python-csv/#writing-csv-files-with-csv

**Comment by HaraHeique** [comment]
### Filtragem dos dados

Filtragem dos  dados antes da etapa de pré-processamento, ou seja, lendo os dados do arquivo txt e obtendo somente as sentenças que não contém caracteres especiais e com tamanhos desejados.

**Faulkner** - _A fábula_

Sentenças totais > 0 e '\n' e ';' = **5917 tokens**
Sentenças > 0 = **5400 tokens**
Sentenças >= 6 = **3540 tokens**
Sentenças >= 10 = **2564 tokens**

Geralmente em todos os livros pega em torno de **40%** a **60%** dos tokens. Como os primeiros tokens podem ser relativos a metadados do livro retirarei em torno de **5%** a **10%** do início e fim do livro. Logo no final será obtido com uma melhor segurança em torno de **30%** a **50%** dos tokens totais do livro pegando **sentenças > 6**.

**OBS**.: **Tokens** é a mesma coisa que **sentenças/frases**. Utilizei tokens porque é como o _nltk_ nomeia o termo.

**Comment by HaraHeique** [comment]
Log de execucao nova base de dados

[log-12000-sentences-200-epochs.txt](https://github.com/HaraHeique/TCC-rede-neural-siamesa/files/5481205/log-12000-sentences-200-epochs.txt)

**Comment by HaraHeique** [comment]
Commits referente as mudanças realizadas para ampliação da base de dados:

- 7379b2c9556ceba83e9d6cf5c5905c9823202eb1;
- be438fe0ccf928309cbcf48d8586e243cf671c24;
- f378bc443502b6da5f37cd0b28bf4abf37560a62;
- 4fefc699af3155a4b6126188d0b2a051468bdfa7.

**Comment by HaraHeique** [comment]
Arquivos de treinamento e previsão gerados a partir da base de dados:

- **Treinamento**: https://github.com/HaraHeique/TCC-rede-neural-siamesa/blob/master/src/data/training/training-12000-sentences.csv;
- **Predição**: https://github.com/HaraHeique/TCC-rede-neural-siamesa/blob/master/src/data/prediction/prediction-120-sentences.csv.

**OBS**.: Estratégia melhor para obter os dados de predição.

**Comment by HaraHeique** [comment]
Refazer isto
**Predição**

180 e 600 (ampliação de 6x) seguindo o mesmo padrão do csv.
Estilo: Frase1, Frase2 em dois arquivos csv.

A primeira coluna sempre do mesmo autor e a segunda coluna aleatória.

**Comment by HaraHeique** [comment]
> Refazer isto
> **Predição**
> 
> 180 e 600 (ampliação de 6x) seguindo o mesmo padrão do csv.
> Estilo: Frase1, Frase2 em dois arquivos csv.
> 
> A primeira coluna sempre do mesmo autor e a segunda coluna aleatória.

Commits referente a este problema:

- 05b1871f4d578915903e6ecb9ec802adbfac08a2
