### ISSUE TITLE
Pesquisar o que significa a variável n_hidden = 50 nas LSTMs.

### ISSUE THREAD

**Issue by Fideliszan** [HaraHeique/TCC-rede-neural-siamesa#12]
O que é n_hidden?

**Comment by HaraHeique** [comment]
@Fideliszan, pelo que eu entendi aquela variável do modelo da LSTM (_n_hidden_) significa o número de estados escondidos. Esta foi uma das melhores respostas que achei na net, até porque na própria documentação do tensorflow eu não entendi bem o que era:

![n_units_lstm](https://user-images.githubusercontent.com/26990166/96535041-5f049780-1267-11eb-82b6-9df9ef585d17.png)

Abaixo está a descrição definida pela documentação do tensorflow:

![docs_tensorflow_units](https://user-images.githubusercontent.com/26990166/96536107-b6a40280-1269-11eb-9862-f89796d040db.png)

Abaixo está um trecho de um código que estava lendo em um [artigo](https://towardsdatascience.com/lstm-by-example-using-tensorflow-feb0c1968537) anexado no último tópico dos links. Perceba que ele utiliza 512 estados escondidos da _LSTM_.

![example_lstm_tensorflow](https://user-images.githubusercontent.com/26990166/96536236-f834ad80-1269-11eb-903f-19db3ee428fd.png)

Abaixo está um parágrafo de uma resposta quando estava pesquisando sobre este parâmetro que achei bem interessante.

![pedaco_importante_lstm_units](https://user-images.githubusercontent.com/26990166/96536382-506baf80-126a-11eb-8f9b-9f81bcdb4fe5.png)


Por fim estes são os links referente ao parâmetro **n_hidden** (chamado de **units** no tensorflow) que pesquisei:

- [tf.keras.layers.LSTM (Documentação Tensorflow)](https://www.tensorflow.org/api_docs/python/tf/keras/layers/LSTM);
- [What is num_units in tensorflow BasicLSTMCell?](https://stackoverflow.com/questions/37901047/what-is-num-units-in-tensorflow-basiclstmcell);
- [Understanding LSTM units vs. cells](https://stats.stackexchange.com/questions/241985/understanding-lstm-units-vs-cells);
- [What is the meaning of “The number of units” in the LSTM cell?](https://www.quora.com/What-is-the-meaning-of-The-number-of-units-in-the-LSTM-cell);
- [What is the relationship between timestep and number hidden unit in LSTM?](https://www.quora.com/What-is-the-relationship-between-timestep-and-number-hidden-unit-in-LSTM);
- [LSTM by Example using Tensorflow](https://towardsdatascience.com/lstm-by-example-using-tensorflow-feb0c1968537).

Qualquer coisa poderia perguntar ao **Daniel** para mais detalhes da quantidade destes estados escondidos que poderiam ser utilizados conforme a necessidade/contexto do problema do trabalho em questão.
