### ISSUE TITLE
Uniformização da linguagem dos algoritmos.

### ISSUE THREAD

**Issue by Fideliszan** [HaraHeique/TCC-rede-neural-siamesa#2]
Lembre-se de adequar a linguagem dos códigos ao TCC. Remover 'question', entre outras coisas.

**Comment by HaraHeique** [comment]
Tanto dos códigos quanto da documentação realizada através do markdown deste repositório do Github

**Comment by HaraHeique** [comment]
Feita as modificações no código e documentação.

**Comment by HaraHeique** [comment]
Links dos commits:

- 8e1da864f383d621bf254e3b573186340120e5d7
- 86b948f6a248483b57613aa7e1c6de4d60e66933
- 8e1da864f383d621bf254e3b573186340120e5d7
